services:
  - type: web
    name: payment-processor
    env: python
    buildCommand: pip3 install -r requirements.txt
    startCommand: gunicorn payment_processor.wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: /opt/render/project/src 