services:
  - type: web
    name: payment-processor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn payment_processor.wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 