"""Add user_id to ContractorPrice

Revision ID: 321098255086
Revises: caa2b615ba7e
Create Date: 2025-04-15 10:39:09.353295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321098255086'
down_revision = 'caa2b615ba7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor_price', schema=None) as batch_op:
        batch_op.drop_constraint('uix_contractor_id_user', type_='unique')
        batch_op.create_unique_constraint('uix_contractor_user', ['contractor_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor_price', schema=None) as batch_op:
        batch_op.drop_constraint('uix_contractor_user', type_='unique')
        batch_op.create_unique_constraint('uix_contractor_id_user', ['contractor_id', 'user_id'])

    # ### end Alembic commands ###
